In [1]:
import torch

import numpy as np
import pandas as pd

In [2]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([5, 6, 7])

In [3]:
a + b
a - b

tensor([-4, -4, -4])

In [4]:
c = torch.tensor([1, 2, 3], dtype=torch.float32)
c

tensor([1., 2., 3.])

In [5]:
d = torch.tensor([1, 2, 3], dtype=torch.int64)
d

tensor([1, 2, 3])

In [9]:
e = torch.empty(2, 2, 2, 3)
e

tensor([[[[-3.8109e-37,  4.5757e-41, -3.1498e-05],
          [ 3.0921e-41,  1.4013e-45,  0.0000e+00]],

         [[-2.6117e-05,  3.0921e-41, -2.9498e-05],
          [ 3.0921e-41,  0.0000e+00,  0.0000e+00]]],


        [[[-2.9575e-05,  3.0921e-41, -1.6546e-06],
          [ 3.0921e-41,  2.8355e+20,  4.5755e-41]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])

In [12]:
torch.rand(2, 2)

tensor([[0.1478, 0.8351],
        [0.4517, 0.8571]])

In [13]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [14]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [15]:
torch.ones(2, 2, dtype=torch.double)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [22]:
a = torch.ones((2,2, 4), dtype=torch.float32)

In [23]:
a.size()

torch.Size([2, 2, 4])

In [24]:
a.shape

torch.Size([2, 2, 4])

In [31]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)

a.add_(b)

tensor([[2., 2.],
        [2., 2.]])

In [32]:
c = a - b
c

tensor([[1., 1.],
        [1., 1.]])

In [33]:
a.mul_(a)

tensor([[4., 4.],
        [4., 4.]])

In [37]:
a.div(a)

tensor([[1., 1.],
        [1., 1.]])

In [38]:
a[:, 0]

tensor([4., 4.])

In [42]:
a = torch.rand(5, 8)
a

tensor([[0.2006, 0.4065, 0.1472, 0.9622, 0.8528, 0.4812, 0.8469, 0.4839],
        [0.2885, 0.6016, 0.9335, 0.3879, 0.8377, 0.6753, 0.4733, 0.6412],
        [0.9871, 0.0902, 0.8217, 0.9546, 0.2936, 0.7557, 0.3114, 0.9736],
        [0.2027, 0.2721, 0.0362, 0.7907, 0.0367, 0.3176, 0.9941, 0.6635],
        [0.7034, 0.2239, 0.5747, 0.4333, 0.4821, 0.9988, 0.5057, 0.3028]])

In [43]:
a[:, 1]

tensor([0.4065, 0.6016, 0.0902, 0.2721, 0.2239])

In [45]:
a.view(40)

tensor([0.2006, 0.4065, 0.1472, 0.9622, 0.8528, 0.4812, 0.8469, 0.4839, 0.2885,
        0.6016, 0.9335, 0.3879, 0.8377, 0.6753, 0.4733, 0.6412, 0.9871, 0.0902,
        0.8217, 0.9546, 0.2936, 0.7557, 0.3114, 0.9736, 0.2027, 0.2721, 0.0362,
        0.7907, 0.0367, 0.3176, 0.9941, 0.6635, 0.7034, 0.2239, 0.5747, 0.4333,
        0.4821, 0.9988, 0.5057, 0.3028])

In [46]:
a.view(8, 5)

tensor([[0.2006, 0.4065, 0.1472, 0.9622, 0.8528],
        [0.4812, 0.8469, 0.4839, 0.2885, 0.6016],
        [0.9335, 0.3879, 0.8377, 0.6753, 0.4733],
        [0.6412, 0.9871, 0.0902, 0.8217, 0.9546],
        [0.2936, 0.7557, 0.3114, 0.9736, 0.2027],
        [0.2721, 0.0362, 0.7907, 0.0367, 0.3176],
        [0.9941, 0.6635, 0.7034, 0.2239, 0.5747],
        [0.4333, 0.4821, 0.9988, 0.5057, 0.3028]])

In [50]:
a.view(-1, 40)
a.shape

torch.Size([5, 8])

In [51]:
a.numpy()

array([[0.20063257, 0.40654856, 0.1471839 , 0.9621553 , 0.852757  ,
        0.4812221 , 0.8468706 , 0.48394573],
       [0.28847432, 0.60160154, 0.9334694 , 0.38793904, 0.8376516 ,
        0.6753176 , 0.4732902 , 0.6412025 ],
       [0.98712385, 0.0901947 , 0.82169014, 0.954598  , 0.29363167,
        0.75567675, 0.3114137 , 0.97361404],
       [0.2026723 , 0.2721128 , 0.03618926, 0.7906701 , 0.03674811,
        0.31760508, 0.9941361 , 0.6634658 ],
       [0.70338285, 0.22391695, 0.57466096, 0.43327296, 0.48213392,
        0.9988335 , 0.50569546, 0.3027566 ]], dtype=float32)

In [54]:
a = torch.ones(2,2)
b = a.numpy()

In [55]:
a.add_(1)

tensor([[2., 2.],
        [2., 2.]])

In [56]:
b

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [61]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [62]:
device

'cuda'

In [63]:
x = torch.ones((3, 4), device=device)

In [68]:
a = a.to(device)

In [70]:
a

tensor([[2., 2.],
        [2., 2.]], device='cuda:0')

In [90]:
x = torch.randn(3, requires_grad=True)

In [91]:
y = x+2

In [92]:
z = y*y*2
print(z)

tensor([ 2.0971, 22.2678,  2.8339], grad_fn=<MulBackward0>)


In [93]:
z = z.mean()

In [94]:
z.backward()

In [95]:
x.grad

tensor([1.3653, 4.4490, 1.5871])