In [1]:
import torch
import numpy as np

np.set_printoptions(precision=3)

In [2]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [3]:
t_ones = torch.ones(2,3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
t_rand = torch.rand(2,3)
t_rand

tensor([[0.2426, 0.3147, 0.8627],
        [0.6252, 0.3912, 0.1005]])

In [5]:
t_a_new = t_a.to(torch.int64)

In [11]:
t = torch.rand(3, 5)
t

tensor([[0.3882, 0.3265, 0.1386, 0.2655, 0.2851],
        [0.0550, 0.7689, 0.0294, 0.8368, 0.6521],
        [0.8511, 0.3567, 0.3229, 0.5205, 0.3305]])

In [12]:

t_tr = torch.transpose(t, 0, 1)
t_tr

tensor([[0.3882, 0.0550, 0.8511],
        [0.3265, 0.7689, 0.3567],
        [0.1386, 0.0294, 0.3229],
        [0.2655, 0.8368, 0.5205],
        [0.2851, 0.6521, 0.3305]])

In [7]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


In [8]:
# Applying mathematical operations to tensors----------------

In [9]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [10]:
t3 = torch.multiply(t1, t2)
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [11]:
t4 = torch.mean(t1, axis=1)
t4

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])

In [12]:
t4 = torch.mean(t1, axis=0)
t4

tensor([-0.1373,  0.2028])

In [13]:
t5 = 2 * torch.rand(5, 2)
t5

tensor([[1.2794, 1.9486],
        [1.6601, 0.0889],
        [0.0492, 0.5177],
        [1.8781, 0.8334],
        [1.4280, 0.5353]])

In [14]:
t5 = 2 * torch.rand(5, 2 ,3)
torch.mean(t5, axis = 0)
torch.mean(t5, axis = 2)

tensor([[1.4360, 0.9997],
        [0.8248, 0.4841],
        [1.4319, 1.0291],
        [1.0910, 1.7145],
        [0.7518, 0.5592]])

In [15]:
t5 = 2 * torch.rand(5,2)
t6 = torch.normal(mean=0, std=1, size=(5,2))
t6

tensor([[ 0.2857,  0.6898],
        [-0.6331,  0.8795],
        [-0.6842,  0.4533],
        [ 0.2912, -0.8317],
        [-0.5525,  0.6355]])

In [16]:
# Element wise multiply------------------

torch.multiply(t5, t6)

tensor([[ 0.4411,  0.5281],
        [-0.9423,  0.9296],
        [-0.9088,  0.5530],
        [ 0.3970, -1.2440],
        [-0.0408,  0.9553]])

In [17]:
# Matrix multiply------------------
torch.matmul(t5, torch.transpose(t6, 0, 1))

tensor([[ 0.9692, -0.3042, -0.7094, -0.1871, -0.3666],
        [ 1.1544, -0.0127, -0.5392, -0.4458, -0.1507],
        [ 1.2210,  0.2319, -0.3559, -0.6278,  0.0413],
        [ 1.4213,  0.4522, -0.2550, -0.8470,  0.1971],
        [ 1.0581,  1.2754,  0.6309, -1.2288,  0.9145]])

In [18]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim =1)
norm_t1

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

In [19]:
# SPLIT, STACK and CONCATENATE Tensors---------------------------

torch.manual_seed(1)
t = torch.rand(6)
t

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])

In [20]:
t_splits = torch.chunk(t, 3)
t_splits

(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))

In [21]:
[item.numpy() for item in t_splits]

[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [22]:
A = torch.ones(3)
B = torch.zeros(2)
C = torch.concatenate([A, B], axis = 0)
C

tensor([1., 1., 1., 0., 0.])

In [23]:
A = torch.ones(3)
B = torch.zeros(3)
C = torch.stack([A, B], axis = 0)
C

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [24]:
A = torch.ones(5,2)
B = torch.zeros(5,1)
C = torch.concatenate([A, B], axis = 1)
C

tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])

In [25]:
A = torch.ones(5,2)
B = torch.zeros(3,2)
C = torch.concatenate([A, B], axis = 0)
C

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
A = torch.ones(5,2)
B = torch.zeros(5,2)
C = torch.stack([A, B], axis = 0)
C.shape

torch.Size([2, 5, 2])

In [27]:
torch.chunk(C, 2)

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]]),
 tensor([[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]]))

In [28]:
torch.split(C, split_size_or_sections=[3,2], dim=1)

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [29]:
# Building input pipelines in PyTorch------------------------



In [30]:
#Creating a PyTorch DataLoader from existing tensors---------------

from torch.utils.data import DataLoader
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)

In [31]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [32]:
data_loader = DataLoader(t, batch_size=3, drop_last=False)

for i, batch in enumerate(data_loader):
    print(f"batch {i} : ", batch)

batch 0 :  tensor([0., 1., 2.])
batch 1 :  tensor([3., 4., 5.])


In [33]:
# Combining two tensors into a joint dataset--------------

torch.manual_seed(1)
t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)

In [34]:
from torch.utils.data import Dataset

class JointDataset(Dataset):

    def __init__(self, x, y) -> None:
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]
    

joint_dataset = JointDataset(t_x, t_y)

for example in joint_dataset:
    print(f"x : {example[0]}, y: {example[1]}")

x : tensor([0.7576, 0.2793, 0.4031]), y: 0
x : tensor([0.7347, 0.0293, 0.7999]), y: 1
x : tensor([0.3971, 0.7544, 0.5695]), y: 2
x : tensor([0.4388, 0.6387, 0.5247]), y: 3


In [35]:
# Shuffle, batch, and repeat---------------------------

torch.manual_seed(1)
data_loader = DataLoader(dataset=joint_dataset, batch_size=2, shuffle=True, drop_last=True)

for i, batch in enumerate(data_loader):
    print(f'batch {i}:', 'x:', batch[0],
        '\n y:', batch[1])

batch 0: x: tensor([[0.3971, 0.7544, 0.5695],
        [0.7576, 0.2793, 0.4031]]) 
 y: tensor([2, 0])
batch 1: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
 y: tensor([1, 3])


In [36]:
for epoch in range(2):
    print(f'epoch {epoch+1}')
    for i, batch in enumerate(data_loader, 1):
        print(f'batch {i}:', 'x:', batch[0],
        '\n    y:', batch[1])

epoch 1
batch 1: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.3971, 0.7544, 0.5695]]) 
    y: tensor([0, 2])
batch 2: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
    y: tensor([1, 3])
epoch 2
batch 1: x: tensor([[0.4388, 0.6387, 0.5247],
        [0.3971, 0.7544, 0.5695]]) 
    y: tensor([3, 2])
batch 2: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]]) 
    y: tensor([0, 1])


In [37]:
class quick_sort:

    def __init__(self, data) -> None:
        self.data = data

    def sort(self, start, end):

        if(start >= end):
            return

        pivot = self.data[start]


        pivot_idx = 0
        for i in range(start+1, end+1):
            if self.data[i] <= pivot:
                pivot_idx += 1

        pivot_idx = pivot_idx+start
        self.data[start], self.data[pivot_idx] = self.data[pivot_idx] ,  self.data[start]
        
        left = start
        right = end
        while left < pivot_idx and right > pivot_idx:
            
            while(self.data[left] <= pivot) :
                left +=1
            
            while(self.data[right] > pivot) :
                right -=1

            if left < pivot_idx and right > pivot_idx :
                self.data[left], self.data[right] = self.data[right] ,  self.data[left]

        
        self.sort (start, pivot_idx-1)
        self.sort (pivot_idx+1, end)

a = quick_sort([34, 1, 56, 23, 1, 34, 90])
a.sort(0, 6)

print(a.data)

[1, 1, 23, 34, 34, 56, 90]


In [38]:
a= [34, 1, 56, 23, 1, 34, 90]

for i in range(len(a)):
    swapped = False
    for j in range(len(a)-1):
        if a[j] > a[j+1]:
            a[j], a[j+1] = a[j+1], a[j]
            swapped=  True

    if swapped == False:
        break

print(a)

[1, 1, 23, 34, 34, 56, 90]


In [39]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)

z = x**2+y**3

z.backward()

print(f"x: {x.grad}")
print(f"y: {y.grad}")

x: 4.0
y: 12.0


In [40]:

import numpy as np

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class emoText(Dataset):

    def __init__(self, path):
        f = open(path)
        lines = f.readlines()

        data = np.array( [ [ line.split("#$#")[0].strip(), 
                             line.split("#$#")[1].strip() ]  for line in lines ] )

        self.sentences = data[:, 0]
        self.labels = data[:, 1]
        np.char.strip( self.sentences)
        np.char.strip( self.labels, chars='\n')

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.sentences[idx], self.labels[idx]

ds = emoText("./Emotion_Dataset_Custom.txt")
dl = DataLoader(ds, batch_size=32, shuffle=True, num_workers=4)


In [43]:
import pandas as pd

f = open("./Emotion_Dataset_Custom.txt")
lines = f.readlines()
data = np.array( [ [ line.split("#$#")[0].strip(), 
                        line.split("#$#")[1].strip() ]  for line in lines ] )

df = pd.DataFrame(columns=["Sentences", "Class"])
df["Sentences"] = data[:, 0]
df["Class"]     = data[:, 1]

df

Sentences    Class
0                                              Hello      joy
1                                                 Hi      joy
2                                        How are you      joy
3                                         I am great      joy
4                           I'm very happy right now      joy
..                                               ...      ...
303              You shouldn't let fear control you.  disgust
304                      Are you afraid of the dark?  disgust
305                        Why is he running scared?  disgust
306                Is the government running scared?  disgust
307  The revealed secret had the CEO running scared.  disgust

[308 rows x 2 columns]

In [44]:
df["Class"].value_counts()

Class
sadness     126
joy         103
fear         34
anger        29
disgust      12
surprise      4
Name: count, dtype: int64

In [51]:
X = df["Sentences"].values
y = df["Class"].values

from sklearn.model_selection import train_test_split
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.4, stratify=y)

In [55]:
df_train = pd.DataFrame(columns=["Sentences", "Class"])
df_train["Sentences"] = X_train
df_train["Class"]     = y_train

df_test = pd.DataFrame(columns=["Sentences", "Class"])
df_test["Sentences"] = X_test
df_test["Class"]     = y_test

In [61]:
df_train["Class"].value_counts()

Class
sadness     75
joy         62
fear        20
anger       17
disgust      7
surprise     3
Name: count, dtype: int64

In [60]:
df_test["Class"].value_counts()

Class
sadness     51
joy         41
fear        14
anger       12
disgust      5
surprise     1
Name: count, dtype: int64

In [64]:
def generate_N_grams(text, ngram=1):
    words = [word for word in text.split(" ")]
    temp = zip(*[ words[i:] for i in range(0, ngram) ])
    print(f"temp : {temp}")
    ans = [ ' '.join(ngram) for ngram in temp ]
    print(f"ans : {ans}")
    return ans

In [65]:
generate_N_grams("The sun rises in the east",2)

temp : <zip object at 0x7f1606ec3f00>
ans : ['The sun', 'sun rises', 'rises in', 'in the', 'the east']


['The sun', 'sun rises', 'rises in', 'in the', 'the east']